=== adrianriley/generic-menu/armenu-schema/src/main/xsd/armenu.xsd
<?xml version="1.0"?>
<!--

-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="menu-config">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="1" minOccurs="1">
                    <xs:element name="menu" type="MenuGroupType"/>
                    <xs:element name="menu-bar" type="MenuBarType"/>
                </xs:choice>
                <xs:element name="commands" type="MenuCommandsType" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="MenuGroupType">
        <xs:complexContent>
            <xs:extension base="AbstractMenuGroupType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="MenuBarType">
        <xs:complexContent>
            <xs:extension base="AbstractMenuGroupType">
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="AbstractMenuGroupType" abstract="true">
        <xs:complexContent>
            <xs:extension base="AbstractMenuItemType">
                <xs:sequence>
                    <xs:element name="items" type="MenuGroupItemsType" minOccurs="1"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="MenuItemType">
        <xs:complexContent>
            <xs:extension base="AbstractMenuItemType">
                <xs:sequence>
                    <xs:element name="command" type="CommandType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:complexType name="MenuGroupItemsType">
        <xs:choice maxOccurs="unbounded" minOccurs="1">
            <xs:element name="menu-group" type="MenuGroupType"/>
            <xs:element name="menu-item" type="MenuItemType"/>
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="AbstractMenuItemType" abstract="true">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="description" type="xs:string" minOccurs="0"/>
            <xs:element name="icon" type="PathType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="MenuCommandsType">
        <xs:choice maxOccurs="unbounded" minOccurs="0">
            <xs:element name="command" type="MenuCommandType"/>
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="MenuCommandType">
        <xs:attribute name="id" type="IdType" use="required"/>
        <xs:attribute name="class" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="IdType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-z0-9$_-]+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="CommandType">
        <xs:sequence>
            <xs:element name="argument" type="xs:string" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="ref" type="IdType" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="PathType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
</xs:schema>

=== adrianriley/generic-menu/armenu/src/test/resources/configuration-test-menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../main/resources/xsd/armenu.xsd">
    <items>
        <menu-group>
            <name>Later group</name>
            <icon>C:/Program Files/a/a.png</icon>
            <items>
                <menu-item>
                    <name>Item 1</name>
                    <command>"C:/Program Files/a/foo-1.exe"</command>
                    <icon>C:/Program Files/a/foo-1.png</icon>
                </menu-item>
                <menu-item>
                    <name>Item 2</name>
                    <command>"C:/Program Files/a/foo-2.exe" "arg with spaces"</command>
                    <icon>C:/Program Files/a/foo-2.gif</icon>
                </menu-item>
            </items>
        </menu-group>
        <menu-group>
            <name>Earlier group</name>
            <icon>C:/Program Files/b/b.png</icon>
            <items>
                <menu-item>
                    <name>Item 2</name>
                    <command>"C:/Program Files/b/bar-1.exe"</command>
                    <icon>C:/Program Files/b/bar-1.png</icon>
                </menu-item>
                <menu-item>
                    <name>Item 1</name>
                    <command>"C:/Program Files/b/bar-2.exe"</command>
                    <icon>C:/Program Files/b/bar-2.gif</icon>
                </menu-item>
                <menu-group>
                    <name>Subgroup</name>
                    <icon>C:/Program Files/a/b/c.png</icon>
                    <items>
                        <menu-item>
                            <name>Item A</name>
                            <command>"C:/Program Files/b/c/baz-1.exe" abc</command>
                            <icon>C:/Program Files/b/c/baz-1.png</icon>
                        </menu-item>
                        <menu-item>
                            <name>Item B</name>
                            <command>"C:/Program Files/b/c/baz-2.exe" def ghi "\"str"</command>
                            <icon>C:/Program Files/b/c/baz-2.gif</icon>
                        </menu-item>
                    </items>
                </menu-group>
                <menu-item>
                    <name>Item 3</name>
                    <command>"C:/Program Files/b/bar-3.exe"</command>
                    <icon>C:/Program Files/b/bar-3.gif</icon>
                </menu-item>
            </items>
        </menu-group>
    </items>
</menu>

=== adrianriley/generic-menu/armenu/src/configuration-test-menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../main/resources/xsd/armenu.xsd">
    <menu>
        <name>Start</name>
        <items>
            <menu-group>
                <name>Later group</name>
                <icon>C:/Program Files/a/a.png</icon>
                <items>
                    <menu-item>
                        <name>Item 1</name>
                        <icon>C:/Program Files/a/foo-1.png</icon>
                        <command ref="Execute">
                            <argument>C:/Program Files/a/foo-1.exe</argument>
                        </command>
                    </menu-item>
                    <menu-item>
                        <name>Item 2</name>
                        <icon>C:/Program Files/a/foo-2.gif</icon>
                        <command ref="Execute">
                            <argument>C:/Program Files/a/foo-2.exe</argument>
                            <argument>arg with spaces</argument>
                        </command>
                    </menu-item>
                </items>
            </menu-group>
            <menu-group>
                <name>Earlier group</name>
                <icon>C:/Program Files/b/b.png</icon>
                <items>
                    <menu-item>
                        <name>Item 2</name>
                        <icon>C:/Program Files/b/bar-1.png</icon>
                        <command ref="Execute">
                            <argument>C:/Program Files/b/bar-1.exe</argument>
                        </command>
                    </menu-item>
                    <menu-item>
                        <name>Item 1</name>
                        <icon>C:/Program Files/b/bar-2.gif</icon>
                        <command ref="Execute">
                            <argument>C:/Program Files/b/bar-2.exe</argument>
                        </command>
                    </menu-item>
                    <menu-group>
                        <name>Subgroup</name>
                        <icon>C:/Program Files/a/b/c.png</icon>
                        <items>
                            <menu-item>
                                <name>Item A</name>
                                <icon>C:/Program Files/b/c/baz-1.png</icon>
                                <command ref="Execute">
                                    <argument>C:/Program Files/b/c/baz-1.exe</argument>
                                    <argument>abc</argument>
                                </command>
                            </menu-item>
                            <menu-item>
                                <name>Item B</name>
                                <icon>C:/Program Files/b/c/baz-2.gif</icon>
                                <command ref="Execute">
                                    <argument>C:/Program Files/b/c/baz-2.exe</argument>
                                    <argument>def</argument>
                                    <argument>ghi</argument>
                                    <argument>&quot;str</argument>
                                </command>
                            </menu-item>
                        </items>
                    </menu-group>
                    <menu-item>
                        <icon>C:/Program Files/b/bar-3.gif</icon>
                        <name>Item 3</name>
                        <command ref="Execute">
                            <argument>C:/Program Files/b/bar-3.exe</argument>
                        </command>
                    </menu-item>
                </items>
            </menu-group>
        </items>
    </menu>
    <commands>
        <command id="Execute" class="uk.co.ariley.armenu.command.ExecuteCommand"/>
    </commands>
</menu-config>

=== adrianriley/generic-menu/armenu-schema/src/test/resources/sample/sample-menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<menu-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../main/resources/xsd/armenu.xsd">
    <menu-bar>
        <items>
            <menu-group>
                <name>Start</name>
                <items>
                    <menu-group>
                        <name>First menu group</name>
                        <icon>C:/Program Files/a/a.png</icon>
                        <items>
                            <menu-item>
                                <name>First menu item</name>
                                <icon>C:/Program Files/a/foo-1.png</icon>
                                <command ref="Execute">
                                    <argument>C:/Program Files/a/foo-1.exe</argument>
                                </command>
                            </menu-item>
                            <menu-item>
                                <name>Second menu item</name>
                                <icon>C:/Program Files/a/foo-2.gif</icon>
                                <command ref="Execute">
                                    <argument>C:/Program Files/a/foo-2.exe</argument>
                                    <argument>arg with spaces</argument>
                                </command>
                            </menu-item>
                        </items>
                    </menu-group>
                    <menu-group>
                        <name>Second menu group</name>
                        <icon>C:/Program Files/b/b.png</icon>
                        <items>
                            <menu-item>
                                <name>First menu item</name>
                                <icon>C:/Program Files/b/bar-1.png</icon>
                                <command ref="Execute">
                                    <argument>C:/Program Files/a/bar-1.exe</argument>
                                </command>
                            </menu-item>
                            <menu-item>
                                <name>Second menu item</name>
                                <icon>C:/Program Files/b/bar-2.gif</icon>
                                <command ref="Execute">
                                    <argument>C:/Program Files/a/bar-2.exe</argument>
                                </command>
                            </menu-item>
                            <menu-group>
                                <name>Second menu group, first subgroup</name>
                                <icon>C:/Program Files/a/b/c.png</icon>
                                <items>
                                    <menu-item>
                                        <name>First subgroup menu item</name>
                                        <icon>C:/Program Files/b/c/baz-1.png</icon>
                                        <command ref="Execute">
                                            <argument>C:/Program Files/a/baz-1.exe</argument>
                                        </command>
                                    </menu-item>
                                    <menu-item>
                                        <name>Second subgroupmenu item</name>
                                        <icon>C:/Program Files/b/c/baz-2.gif</icon>
                                        <command ref="Execute">
                                            <argument>C:/Program Files/a/baz-1.exe</argument>
                                            <argument>def</argument>
                                            <argument>ghi</argument>
                                            <argument>&quot;str</argument>
                                        </command>
                                    </menu-item>
                                </items>
                            </menu-group>
                            <menu-item>
                                <name>Third menu item</name>
                                <icon>C:/Program Files/b/bar-3.gif</icon>
                                <command ref="Execute">
                                    <argument>C:/Program Files/a/bar-3.exe</argument>
                                </command>
                            </menu-item>
                        </items>
                    </menu-group>
                </items>
            </menu-group>
        </items>
    </menu-bar>
    <commands>
        <command id="Execute" class="uk.co.ariley.armenu.command.ExecuteCommand"/>
    </commands>
</menu-config>
